### ISSUE TITLE
Consensus Configuration with Agents 

### ISSUE THREAD

**Issue by landenf** [landenf/AIAA_PHM_Tool#4]
# Todo

- [x] Implement Mav Link Sending and Receiving for Debug Logs
- [x] Set up a pipeline for creating, compressing, and sending reports based on consensus
- [x] Interpreting Consensus at the GSC
