### ISSUE TITLE
Code Cleanup

### ISSUE THREAD

**Issue by landenf** [landenf/AIAA_PHM_Tool#6]
# Todo

- [ ] Clean up function names and make sure to only include relevant parameters
- [ ] Clean up function structure 
- [ ] Clean up documentation and comments
