### ISSUE TITLE
Container Deployment

### ISSUE THREAD

**Issue by landenf** [landenf/AIAA_PHM_Tool#8]
# Todo

- [ ] Research how to deploy to a container registry
- [ ] How to deploy with SITL
- [ ] How to deploy on hardware.
